### ISSUE TITLE
Standalone usage?

### ISSUE THREAD

**Issue by dantman** [cdbattags/lua-resty-jwt#39]
lua-resty-jwt is the only JWT library for Lua listed on jwt.io?

The library seems to be designed for use in the Nginx Lua plugin.

Is this library usable as a standalone jwt library for Lua, outside of nginx?

**Comment by northlander** [comment]
Sure it can be used outside of Nginx. However it depends on a lot of OpenResty packages. It works fine using the "resty" command line tool to load the lua-script instead of lua/luajit. 

`resty my-lua-script-using-lua-resty-jwt.lua`

You can probably collect all dependencies on your own via luarocks etc and fire up a standalone version. I haven't tried though.

**Comment by cdbattags** [comment]
@northlander, thanks for the response! @dantman, let us know if you need more clarification. Closing for now.
